# Generated by Django 4.2.14 on 2024-08-16 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_remove_cart_created_at_remove_cart_is_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_title',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.cart'),
        ),
    ]
